DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS user_role;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(30),
  age INTEGER,
  birthdate VARCHAR(10)
);

CREATE TABLE role (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(15),
  description VARCHAR(30)
);

CREATE TABLE user_role (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER REFERENCES user(id),
  role_id INTEGER REFERENCES role(id)
);
